<a href="https://colab.research.google.com/github/soetgdeznsgk/UN-Gamejam2/blob/main/Quiz1/psuarezv_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python --version
import numpy as np

print('NumPy', np.__version__)

Python 3.10.12
NumPy 1.23.5


In [ ]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzz(x):
    answer =""
    if(x%3 == 0 and x%5!=0):
      answer="Fizz!"
    elif(x%5==0 and x%3!=0):
      answer = "Buzz!"
    elif(x%5==0 and x%3==0):
      answer = "FizzBuzz!"
    else:
      answer = "..."
    return answer

In [ ]:
print(FizzBuzz(3))
print(FizzBuzz(7))
print(FizzBuzz(5))
print(FizzBuzz(11))
print(FizzBuzz(15))

Fizz!
...
Buzz!
...
FizzBuzz!


In [ ]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzzList(n):

    ans = []

    for i in range(1,n+1):
      ans.append(FizzBuzz(i))

    return ans


In [ ]:
print(FizzBuzzList(5))
print(FizzBuzzList(-30))

['...', '...', 'Fizz!', '...', 'Buzz!']
[]


In [ ]:
import numpy as np

X = np.array([1.2,3.2,4.3,5.6])
print(X.mean())
print(X.std())


3.5749999999999997
1.6130328576938535


In [ ]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def standarize(X):
  X_standarized = (X - np.mean(X)) / np.std(X)# only one line of code
  return X_standarized

In [ ]:
import numpy as np
A = np.array([
    [1, 0, 2, 9, 2],
    [9, 2, 6, 5, 7],
    [6, 4, 3, 4, 7]

])

print(A.astype(float))

print(np.diag(A))

print(np.diag(np.diag(A)))

[[1. 0. 2. 9. 2.]
 [9. 2. 6. 5. 7.]
 [6. 4. 3. 4. 7.]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def main_diagonal_matrix(A):
  D = np.diag(np.diag(A)).astype(float)# only one line of code
  return D